# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: centos:7

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  # before_script:
  #   - apt update && apt -y install make autoconf
  script:
    - wget --no-check-certificate https://cmake.org/files/v3.12/cmake-3.12.0-Linux-x86_64.tar.gz
    - tar -xvf cmake-3.12.0-Linux-x86_64.tar.gz > /dev/null
    - mv cmake-3.12.0-Linux-x86_64 cmake-install
    - pwd_path=$(pwd)
    - PATH=${pwd_path}/cmake-install:${pwd_path}/cmake-install/bin:$PATH
    - chmod +x scripts/buildgrpc.sh
    - sh scripts/buildgrpc.sh
  artifacts:
    paths:
      - find . -name "stdarray"
      # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
      # cache:
      #   paths:
      #     - "*.o"

# run tests using the binary built before
#test:
#  stage: test
#  script:
#    - ./runmytests.sh
